#!/usr/bin/python3

import math
import sys

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def factorize_rsa(n):
    for i in range(2, n):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return i, n // i
    return n, 1

def main(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize_rsa(n)
            print(f"{n}={q}*{p}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./rsa <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)
