#!/usr/bin/python3

#!/usr/bin/python3

from sys import argv
import random

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def pollards_rho(n):
    if n % 2 == 0:
        return 2

    x = random.randint(1, n - 1)
    y = x
    c = random.randint(1, n - 1)
    d = 1

    f = lambda x: (x ** 2 + c) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)

    return d

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end='')

        if num % 2 == 0:
            print("{}*2".format(num // 2))
            continue

        factor = pollards_rho(num)
        if factor == num:
            print("{}*{}".format(factor, 1))
        else:
            print("{}*{}".format(factor, num // factor))
